resilience4j:
  circuitbreaker:
    instances:
      payment-service:
        failure-rate-threshold: 80
        wait-duration-in-open-state: 1000
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 10

    
      
    
      